const navButtons = document.querySelectorAll('.nav-link');
const views = document.querySelectorAll('.view');
const modal = document.getElementById('session-modal');
const toast = document.getElementById('toast');
const micButton = document.getElementById('mic');
const answerBox = document.getElementById('answer-box');
const textarea = answerBox.querySelector('textarea');
const hint = document.getElementById('hint');
const timerEl = document.getElementById('timer');
const articleSlots = ['world','business'];
let editionKey = new Date().toISOString().slice(0,10), peer=null, dataChannel=null, localStream=null, remoteAudio=null, sessionStartedAt=0, timerId=null, connected=false;
function showToast(m){toast.textContent=m;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3000)}
function ratingKey(id){return `parlons-${editionKey}-rating-${id}`} function readKey(id){return `parlons-${editionKey}-opened-${id}`}
function showRatingForm(id){const a=document.querySelector(`[data-ratings="${id}"]`);a.classList.remove('pending-rating');a.innerHTML=`<div class="rating-form"><label>Intérêt<select data-rating-kind="interest"><option value="">Choisir</option>${[1,2,3,4,5].map(n=>`<option>${n}</option>`).join('')}</select></label><label>Difficulté<select data-rating-kind="difficulty"><option value="">Choisir</option>${[1,2,3,4,5,6,7,8,9,10].map(n=>`<option>${n}</option>`).join('')}</select></label></div>`;a.querySelectorAll('select').forEach(s=>s.addEventListener('change',()=>saveRatings(id)))}
function saveRatings(id){const a=document.querySelector(`[data-ratings="${id}"]`),i=a.querySelector('[data-rating-kind="interest"]').value,d=a.querySelector('[data-rating-kind="difficulty"]').value;if(!i||!d)return;localStorage.setItem(ratingKey(id),JSON.stringify({interest:i,difficulty:d}));a.innerHTML=`<span class="rating-saved">✓ Ton avis : intérêt ${i}/5 · difficulté ${d}/10</span>`;showToast('Ton avis est enregistré.')}
function restoreArticleState(){let n=0;articleSlots.forEach(id=>{const a=document.querySelector(`[data-ratings="${id}"]`),l=document.querySelector(`[data-article="${id}"]`),r=localStorage.getItem(ratingKey(id)),o=localStorage.getItem(readKey(id))==='true';if(o){n++;showRatingForm(id)}else a.innerHTML='<span>Ouvre l’article avant de l’évaluer.</span>';if(r){const x=JSON.parse(r);a.innerHTML=`<span class="rating-saved">✓ Ton avis : intérêt ${x.interest}/5 · difficulté ${x.difficulty}/10</span>`}l.addEventListener('click',()=>{localStorage.setItem(readKey(id),'true');showRatingForm(id);updateReadingProgress()})});updateReadingProgress(n)}
function updateReadingProgress(n){const x=n??articleSlots.filter(id=>localStorage.getItem(readKey(id))==='true').length;if(x===2){document.getElementById('reading-step').textContent='✓';document.getElementById('reading-step').classList.add('done');document.getElementById('reading-status').textContent='ÉTAPE 1 · TERMINÉE';document.getElementById('reading-complete').textContent='Bien joué !';document.getElementById('daily-progress').textContent='1/3'}}
function formatPublished(v){const d=new Date(v);return Number.isNaN(d.getTime())?'Aujourd’hui':new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'long'}).format(d)}
async function loadDailyArticles(){try{const r=await fetch(`articles.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw 0;const d=await r.json();editionKey=d.updated||editionKey;d.articles.forEach(a=>{document.getElementById(`article-title-${a.slot}`).textContent=a.title;document.getElementById(`article-source-${a.slot}`).textContent=`${a.source} · ${formatPublished(a.published)}`;document.getElementById(`article-summary-${a.slot}`).textContent=a.label;document.getElementById(`article-link-${a.slot}`).href=a.url})}catch{showToast('Les liens du jour n’ont pas pu être actualisés.')}restoreArticleState()}
function setStatus(t){hint.textContent=t} function formatTime(ms){const s=Math.max(0,Math.floor(ms/1000));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}function updateTimer(){const left=Math.max(0,1200000-(Date.now()-sessionStartedAt));timerEl.textContent=formatTime(left);if(!left){showToast('Les 20 minutes sont terminées.');closeSession()}}
function sendEvent(e){if(dataChannel?.readyState==='open')dataChannel.send(JSON.stringify(e))} function sendText(t){sendEvent({type:'conversation.item.create',item:{type:'message',role:'user',content:[{type:'input_text',text:t}]}});sendEvent({type:'response.create'})}
let coachLine=null;function box(){let b=document.getElementById('live-transcript');if(!b){b=document.createElement('div');b.id='live-transcript';b.className='live-transcript';modal.querySelector('.modal-card').appendChild(b)}return b}function esc(s){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}function userTranscript(t){const p=document.createElement('p');p.innerHTML=`<b>Valérie :</b> ${esc(t)}`;box().appendChild(p)}function coachDelta(t){if(!coachLine){coachLine=document.createElement('p');coachLine.dataset.text='';coachLine.innerHTML='<b>Parlons :</b> ';box().appendChild(coachLine)}coachLine.dataset.text+=t;coachLine.innerHTML='<b>Parlons :</b> '+esc(coachLine.dataset.text);box().scrollTop=box().scrollHeight}
function handleEvent(e){let d;try{d=JSON.parse(e.data)}catch{return}if(d.type==='session.created'||d.type==='session.updated'){connected=true;setStatus('Je t’écoute. Tu peux poser une question, donner ton avis ou ne pas être d’accord.')}if(d.type==='conversation.item.input_audio_transcription.completed')userTranscript(d.transcript);if(d.type==='response.output_audio_transcript.delta')coachDelta(d.delta);if(d.type==='response.output_audio_transcript.done')coachLine=null;if(d.type==='error')showToast(d.error?.message||'La conversation a rencontré un problème.')}
async function startRealtime(){setStatus('Connexion à Parlons…');micButton.disabled=true;const articles=articleSlots.map(id=>({title:document.getElementById(`article-title-${id}`).textContent,source:document.getElementById(`article-source-${id}`).textContent}));const tr=await fetch('/api/realtime-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({articles})});if(!tr.ok){const x=await tr.json().catch(()=>({}));throw Error(x.error||'Impossible de démarrer la conversation.')}const {client_secret}=await tr.json();peer=new RTCPeerConnection();remoteAudio=new Audio();remoteAudio.autoplay=true;peer.ontrack=e=>{remoteAudio.srcObject=e.streams[0];remoteAudio.play().catch(()=>{})};localStream=await navigator.mediaDevices.getUserMedia({audio:true});localStream.getTracks().forEach(t=>peer.addTrack(t,localStream));dataChannel=peer.createDataChannel('oai-events');dataChannel.addEventListener('message',handleEvent);dataChannel.addEventListener('open',()=>{connected=true;sendEvent({type:'response.create'})});const offer=await peer.createOffer();await peer.setLocalDescription(offer);await new Promise(r=>{if(peer.iceGatheringState==='complete')r();else peer.addEventListener('icegatheringstatechange',()=>{if(peer.iceGatheringState==='complete')r()})});const s=await fetch('https://api.openai.com/v1/realtime/calls',{method:'POST',headers:{Authorization:`Bearer ${client_secret}`,'Content-Type':'application/sdp'},body:peer.localDescription.sdp});if(!s.ok)throw Error('La connexion audio sécurisée avec OpenAI a échoué.');await peer.setRemoteDescription({type:'answer',sdp:await s.text()});micButton.disabled=false;micButton.textContent='● Microphone actif';setStatus('Je t’écoute.')}
async function openSession(){modal.hidden=false;document.body.style.overflow='hidden';sessionStartedAt=Date.now();timerId=setInterval(updateTimer,500);timerEl.textContent='20:00';document.getElementById('live-transcript')?.remove();try{await startRealtime()}catch(e){showToast(e.message||'Impossible de démarrer.');closeSession()}}
function closeSession(){clearInterval(timerId);timerId=null;if(localStream)localStream.getTracks().forEach(t=>t.stop());if(dataChannel)dataChannel.close();if(peer)peer.close();localStream=null;dataChannel=null;peer=null;connected=false;micButton.disabled=false;micButton.textContent='● Parler en français';modal.hidden=true;document.body.style.overflow='';if(remoteAudio)remoteAudio.pause();remoteAudio=null}
navButtons.forEach(b=>b.addEventListener('click',()=>{navButtons.forEach(x=>x.classList.remove('active'));views.forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.view).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}));
document.getElementById('start-session').addEventListener('click',openSession);document.getElementById('close-modal').addEventListener('click',closeSession);modal.addEventListener('click',e=>{if(e.target===modal)closeSession()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)closeSession()});document.getElementById('show-answer').addEventListener('click',()=>{answerBox.hidden=false;document.getElementById('show-answer').hidden=true;textarea.focus()});document.getElementById('send-answer').addEventListener('click',()=>{const t=textarea.value.trim();if(!t)return;textarea.value='';sendText(t)});micButton.addEventListener('click',()=>{if(!connected)openSession()});loadDailyArticles();
